<?php

namespace Modules\InventoryManagement\Http\Controllers;

use App\Helper\ResponseMessage;
use App\Http\Controllers\Controller;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Modules\InventoryManagement\Models\Product;
use Modules\InventoryManagement\Transformers\products;

class ProductController extends Controller
{
    public function __construct(Product $model)
    {
        parent::__construct($model);
    }

    public function Save(Request $request){
        $temp = new Product();
        $temp->fill($request->all());
        $temp->save();
        foreach ($request->file_urls as $path) {
            $temp->attachments()->create([
                'path' => $path,
            ]);
        }
        return ResponseMessage::successResponse("done", $temp, 201);
    }

    public function getOne($id)
    {
        return  ResponseMessage::successResponse(
            "done",
            new products(Product::findorfail($id)),
            201); // TODO: Change the autogenerated stub
    }


}
