<?php

namespace Modules\InventoryManagement\Http\Controllers;

use App\Helper\ResponseMessage;
use App\Http\Controllers\Controller;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Modules\InventoryManagement\Models\Product;
use Modules\InventoryManagement\Transformers\products;

class ProductController extends Controller
{
    public function __construct(Product $model)
    {
        parent::__construct($model);
    }

    public function Save(Request $request){
        $temp = new Product();
        $temp->fill($request->all());
        $temp->save();
        foreach ($request->file_urls as $path) {
            $temp->attachments()->create([
                'path' => $path,
            ]);
        }
        return ResponseMessage::successResponse("done", $temp, 201);
    }

    public function getOne($id)
    {
        return  ResponseMessage::successResponse(
            "done",
            new products(Product::findorfail($id)),
            201); // TODO: Change the autogenerated stub
    }

    public function getMarketProducts(){
        $products = Product::paginate(9); // Load attachments and paginate
        return ResponseMessage::successResponse(
            "done",
            [
                'data' => products::collection($products), // Paginated data
                'pagination' => [
                    'current_page' => $products->currentPage(),
                    'last_page' => $products->lastPage(),
                    'per_page' => $products->perPage(),
                    'total' => $products->total(),
                    'next_page_url' => $products->nextPageUrl(),
                    'prev_page_url' => $products->previousPageUrl(),
                ]
            ],
            200
        );
    }
}
